config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :panelladike2017s
  resources :suggested_posts
  resources :panelladikes
  resources :xeimwnas
  resources :kalokairis
  resources :latests
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'	
  devise_for :models, controllers: {sessions: 'models/sessions'}

  resources :students do
    put :order, on: :collection
  end

  get "home"=> "static_pages#home"
  
  get "lista" => "students#list"
  get "taftotita" => "static_pages#taftotita"
  get "frontistirio" => "static_pages#frontistirio"
  get "ecdl" => "static_pages#ecdl"
  get "contact" => "static_pages#contact"
  get "epitixontes"=>"students#index"
  get "dialekse_kateuthinsi"=>"static_pages#dialekse_kateuthinsi"
  get "analitika_thetiki"=>"static_pages#analitika_thetiki"

  get "programma" => "static_pages#programma"
  get "programma_lukeiou" => 'static_pages#lukeio'

  get "themata_ximeia"=>'static_pages#ximeia'
  get "themata_fusiki"=>'static_pages#fusiki'
  get "themata_mathimatika"=>'static_pages#mathimatika'
  get "themata_glwssa"=>'static_pages#glwssa'
  get "themata_latinika"=>'static_pages#latinika'
  get "themata_istoria"=>'static_pages#istoria'
  get "themata_biologia"=>'static_pages#biologia'
  get "themata_aoth"=>'static_pages#aoth'
  get "themata_arxaia"=>'static_pages#arxaia'
  get "themata_aep"=>'static_pages#aep'
  

  get "anthropistikes"=>'static_pages#anthropistikes'
  get "thetikes"=>'static_pages#thetikwn'
  get "oikonomias_pliroforikis"=>'static_pages#oikonomias'
 
 
  get "prosfora" => 'static_pages#prosfora'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def taftotita
  end

  def frontistirio
  end

  def kalokairi
  end

  def programma
  end

  def lukeio
  end


  def xeimwnas
  end

  def panelladikes
  end

  def ximeia
  end

  def fusiki
  end

  def mathimatika
  end

  def glwssa
  end

  def latinika
  end

  def istoria
  end

  def biologia
  end

  def aoth
  end

  def arxaia
  end

  def aep
  end

  def ecdl
  end

  def contact
  end

  def epitixontes
  end

  def dialekse_kateuthinsi
  end

  def analitika_thetiki
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/aep.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις ΑΕΠΠ
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("aep_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("aep_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/analitika_thetiki.html.erb
<% provide(:title, 'Τεχνολογικών και Θετικών σπουδών') %>
<% provide(:sbHeader, 'Προσανατολισμοί') %>
<% content_for :sbMenu do %>
  <%= link_to 'Οικονομικών και Πληροφορικής', '#' %>
  <%= link_to 'Ανθρωπιστικών και Κοινωνικών σπουδών ', '#' %>
  <%= link_to 'Σπουδών ζωής και υγείας', '#' %>
<% end %>

<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Παροχές</h1>        
        </div>
        <p>
        </p>
        <p>
        </p>
        <small>
        </small>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/aoth.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις Α.Ο.Θ
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("aoth_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("aoth_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/biologia.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις Βιολογία
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("biologia_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("biologia_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
        <p>
        Θέματα και απαντήσεις Βιολογία Γ.Π
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("biologia_themata_genikis.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("biologia_apantiseis_genikis.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/fusiki.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις Φυσική
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("fusiki_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("fusiki_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/glwssa.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις Γλώσσας
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("glwssa_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("glwssa_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
        <p>
        Θέματα και απαντήσεις Γλώσσας ΕΠΑΛ
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("glwssa_themata_epal.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("glwssa_apantiseis_epal.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/home.html.erb
<!-- Start front img -->
<div class="img-front">
  <%= image_tag 'header.jpg', alt: 'img-front' %>
</div>
<!-- End front img -->

<!-- Start katefthinseis section -->
<section class="sections">
  <div class="container">
    <div class="page-header">
      <h1>Κατευθύνσεις</h1>
    </div>

    <div class="row">

      <div class="col-xs-12 col-md-3 item">
        <%=link_to image_tag("kateuthinseis/anthropistikes.jpg", alt: 'random-img', class: 'img-responsive'), anthropistikes_path %>
        <h2><%= link_to 'Ανθρωπιστικές', anthropistikes_path %></h2>
      </div> <!-- /.col item -->

      <div class="col-xs-12 col-md-3 item">
        <%=link_to image_tag('kateuthinseis/texnologika-oikonomias.png', alt: 'random-img', class: 'img-responsive'), oikonomias_pliroforikis_path %>
        <h2><%= link_to 'Πληροφορικής - Οικονομικών', oikonomias_pliroforikis_path%></h2>
      </div> <!-- /.col item -->

      <div class="col-xs-12 col-md-3 item">
        <%=link_to image_tag("kateuthinseis/texnologikwn-thetikwn.png", alt: 'random-img', class: 'img-responsive'), thetikes_path %>
        <h2><%= link_to 'Τεχνολογικών - Θετικών', thetikes_path%></h2>
      </div> <!-- /.col item -->

      <div class="col-xs-12 col-md-3 item">
        <%=link_to image_tag('kateuthinseis/ygeias-zwis.png', alt: 'random-img', class: 'img-responsive'), thetikes_path %>
        <h2><%= link_to 'Υγείας - Ζωής', thetikes_path%></h2>
      </div> <!-- /.col item -->
    </div> <!-- /.row -->
  </div> <!-- /.container -->
</section>

<!-- End katefthinseis section -->

<!-- Start epityxontes section -->
<section class="succeeders">
  <div class="container">
    <div class="page-header">
      <h1>Επιτυχόντες</h1>
    </div>

    <div id="carousel" class="owl-carousel epitixontes">
      <% Student.all.each do |img| %>
        <% img.student_attachments.each do |a| %>
        <div class="r-item">
          <%= image_tag a.avatar_url, alt: 'epitixon-img', class: 'img-responsive' %>
          <h2><%= img.first_name%> <%= img.last_name %></h2>
          <h3><%= img.school %></h3>
        </div>
      <%end%>
      <% end %>
    </div>
      <div class="text-center">
        <%= link_to 'Αναλυτικά', epitixontes_path, class: 'btn btn-lg btn-primary btn-more' %>
      </div>  
    </div> <!-- /.row -->
  </div><!-- /.container -->
</section>

<!-- End epityxontes section -->

<!-- Start diafora section -->
<section class="several">
  <div class="container">
    <div class="row">

      <div class="col-md-8 col-md-offset-2 inline-item">

        <div class="col-md-8 col-md-offset-2">
          <h2>Οδηγός Σπουδών</h2>
          <p> Όλες οι πληροφορίες για τις κατευθύνσεις και τα μαθήματα βαρύτητας για το κάθε επιστημονικό πεδίο. </p>
          <div class="row">
          <div class="text-center">
          <%= link_to 'Αναλυτικά',anthropistikes_path , class: 'btn btn-primary' %>
          </div>
        </div>
      </div> 
      
        <div class="col-md-8 col-md-offset-2">
          <h2>Μάθετε τα νέα μας</h2>
          <p> Διαβάστε για νέα και ανακοινώσεις αναλυτικά </p>
          <div class="row">
          <div class="text-center">
          <%= link_to 'Αναλυτικά',latests_path , class: 'btn btn-primary' %>
          </div>
          </div>
        </div>

        <div class="col-md-8 col-md-offset-2">
          <h2>Επικοινωνία </h2>
          <p> Επικοινωνήστε μαζί μας και μάθετε λεπτομέριες για το ορόσημο </p>
          <div class="row">
          <div class="text-center">
          <%= link_to 'Αναλυτικά',latests_path , class: 'btn btn-primary' %>
          </div>
          </div>
        </div>
      </div> <!-- /.col inline-item -->
    </div> <!-- /.row -->
  </div><!-- /.container -->
</section>

<section class="succeeders">
  <div class="container">
    <div class="page-header">
      <h1>ECDL</h1>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 inline-item">
        <div class="col-md-12">
          <p> Το ΟΡΟΣΗΜΟ ΠΕΙΡΑΙΑ σε συνεργασία με το <%=link_to "Click Planet",'http://www.clickplanet.gr/'%> παρέχει ένα ανταγωνιστικό πακέτο για όλους</p>
        </div>
        </div>
      </div>
    <div class="row">
      <div class="text-center">
        <%= link_to 'Αναλυτικά', ecdl_path , class: 'btn btn-lg btn-primary btn-more' %>
      </div>  
    </div> <!-- /.row -->
  </div><!-- /.container -->
</section>
<!-- End diafora section -->


<script type="text/javascript">
  $(document).ready(function(){
   $("#carousel").owlCarousel({   
      navigation: true,
      navigationText: [
        "<i class='fa fa-chevron-left'></i>",
        "<i class='fa fa-chevron-right'></i>"
        ],
      autoPlay: 4000,
      items: 4,
      pagination: false,
      responsive: true
    });


  });
</script>

app/views/static_pages/latinika.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις Λατινικά
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("latinika_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("latinika_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/mathimatika.html.erb
<% provide(:title, 'Πανελλαδικές Εξετάσεις') %>
<% provide(:sbHeader, 'Θέματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Χημεία', themata_ximeia_path %>
  <%= link_to 'Φυσική',  themata_fusiki_path%>
  <%= link_to 'Μαθημματικά', themata_mathimatika_path%>
  <%= link_to 'Γλώσσα',  themata_glwssa_path%>
  <%= link_to 'Λατινικά',  themata_latinika_path%>
  <%= link_to 'Ιστορία',  themata_istoria_path%>
  <%= link_to 'Βιολογία',  themata_biologia_path%>
  <%= link_to 'Α.Ο.Θ',  themata_aoth_path%>
  <%= link_to 'Αρχαία', themata_arxaia_path%>
  <%= link_to 'ΑΕΠΠ',  themata_aep_path%>
<% end %>
<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Θέματα και απαντήσεις πανελλαδικών εξετάσεων:</h1>
        </div>
        <p class="lead">
        </p>
        <p>
        Θέματα και απαντήσεις Μαθημματικά προσανατολισμού
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("mathimatika_themata_kate.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("mathimatika_apantiseis_kate.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
        <p>
        Θέματα και απαντήσεις Μαθημματικά Γ.Π
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("mathimatika_themata_genikis.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("mathimatika_apantiseis_genikis.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
        <p>
        Θέματα και απαντήσεις Μαθηματικά ΕΠΑΛ
        </p>
        <div class="table-responsive">
          <table class="table">
            <tr class="warning">
              <th>Έτος</th>
              <th>Θέματα</th>
              <th>Απαντήσεις</th>
            </tr>
            <tr class="warning">
              <td>2016</td>
              <td><%= link_to "Θέματα", asset_path("mathimatika_themata_epal.pdf"), :class=>"links"%></td> 
              <td><%= link_to "Απαντήσεις", asset_path("mathimatika_apantiseis_epal.pdf"), :class=>"links"%></td> 
            </tr>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>

app/views/static_pages/taftotita.html.erb
<% provide(:title, 'Ταυτότητα') %>
<% provide(:sbHeader, 'Ταυτότητα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Οι Καθηγητές', taftotita_path %>
  <%= link_to 'Το φροντιστήριο', frontistirio_path %>
<% end %>

<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>

      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1>Καθηγητές</h1>        
        </div>
        <p class="lead">
        </p>
        <p>
        Είμαστε τα πρώτα φροντιστήρια αποκλειστικά για σχολές με μεγάλο συναγωνισμό. Λειτουργούμε πάνω από 40 χρόνια με επιτυχίες στις πιο δύσκολες σχολές των Α.Ε.Ι, γιατί μας ενδιαφέρει η ποιότητα. Στο διάστημα αυτό εκπαιδεύουμε περισσότερους από 35.000 μαθητές. Κάθε χρόνο πετυχαίνουμε ένα ποσοστό(ανάλογα με τη σχολή) 85-98% των μαθητών μας να γίνονται φοιτητές. Το ποσοστό αυτό είναι αποτέλεσμα μεθοδικής δουλειάς, που βασίζεται σε ένα μελετημένο πρόγραμμα διδασκαλίας. Φιλοδοξούμε στην οργάνωση του ορθού τρόπου σκέψης και στη μεθόδευση του τρόπου μελέτης των σπουδαστών μας, που θα τους βοηθήσει στη μελλοντική επιστημονική σταδιοδρομία τους.
        </p>
        <br/><br/>
        <h3>Διεύθυνση</h3>
        <p class="lead">Χημείας - Βιολογίας: ΔΕΜΕΝΑΓΑΣ ΠΟΛΥΧΡΟΝΗΣ</p>
        <p class="lead">Φυσικής: ΛΑΜΠΡΟΠΟΥΛΟΣ ΓΕΩΡΓΙΟΣ</p>
        <p class="lead">Νέων Ελληνικών: ΜΟΥΣΟΥΛΗΣ ΓΙΑΝΝΗΣ</p>
        <p class="lead">Αρχαίων - Λατινικών: ΣΑΡΜΠΑΝΗ ΕΙΡΗΝΗ</p>
        <p class="lead">Μαθηματικών: ΣΩΤΗΡΟΠΟΥΛΟΥ ΔΕΣΠΟΙΝΑ</p>
        <br/>
        <h3>Διεύθυνση Σπουδών</h3>
        <p class="lead">ΠΑΓΚΑΛΗΣ ΔΗΜΗΤΡΗΣ</p>
        <br/>
        <h3>Ιδρυτής</h3>
        <p class="lead">ΖΥΡΜΠΑΣ ΑΝΔΡΕΑΣ</p>
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</section>