config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :panelladike2017s
  resources :suggested_posts
  resources :panelladikes
  resources :xeimwnas
  resources :kalokairis
  resources :latests
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'	
  devise_for :models, controllers: {sessions: 'models/sessions'}

  resources :students do
    put :order, on: :collection
  end

  get "home"=> "static_pages#home"
  
  get "lista" => "students#list"
  get "taftotita" => "static_pages#taftotita"
  get "frontistirio" => "static_pages#frontistirio"
  get "ecdl" => "static_pages#ecdl"
  get "contact" => "static_pages#contact"
  get "epitixontes"=>"students#index"
  get "dialekse_kateuthinsi"=>"static_pages#dialekse_kateuthinsi"
  get "analitika_thetiki"=>"static_pages#analitika_thetiki"

  get "programma" => "static_pages#programma"
  get "programma_lukeiou" => 'static_pages#lukeio'

  get "themata_ximeia"=>'static_pages#ximeia'
  get "themata_fusiki"=>'static_pages#fusiki'
  get "themata_mathimatika"=>'static_pages#mathimatika'
  get "themata_glwssa"=>'static_pages#glwssa'
  get "themata_latinika"=>'static_pages#latinika'
  get "themata_istoria"=>'static_pages#istoria'
  get "themata_biologia"=>'static_pages#biologia'
  get "themata_aoth"=>'static_pages#aoth'
  get "themata_arxaia"=>'static_pages#arxaia'
  get "themata_aep"=>'static_pages#aep'
  

  get "anthropistikes"=>'static_pages#anthropistikes'
  get "thetikes"=>'static_pages#thetikwn'
  get "oikonomias_pliroforikis"=>'static_pages#oikonomias'
 
 
  get "prosfora" => 'static_pages#prosfora'

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_attachments , dependent: :destroy
  accepts_nested_attributes_for :student_attachments, :allow_destroy => true

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates :year, presence: true, format: {with: /\d{4}/}
  validates :priority, numericality:{less_than_or_equal: 4}

  default_scope -> {order(priority: :asc)}
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_model!, except: [:index]

  def list
    @students = Student.all
  end
  def order
    params[:order].each do |key,value|
      Student.find(value[:id]).update_attribute(:priority,value[:position])
    end

    render :nothing =>true
  end
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @students = Student.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
    if @student.save 
       params[:student_attachments]['avatar'].each do |a|
          @student_attachment = @student.student_attachments.create!(:avatar => a)
        end
     format.html { redirect_to @student, notice: 'Property was successfully created.' } 
     format.json { render :show, status: :created, location: @student } 

      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :school, :year, :priority, :student_attachments_attributes => [:student_id, :avatar])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<% provide(:title, 'Διαχειριστικό menu') %>
<% provide(:sbHeader, 'Διαχειριστικό menu') %>
<% content_for :sbMenu do %>
  <%= link_to 'Επιτυχόντες', students_path %>
  <%= link_to 'Έξοδος', destroy_model_session_path , :method => :delete %>
    <% end %>

<%= form_for(@student, :html => {:multipart => true}) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<section class="identity">

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav'%>
      </div>
     <div class="col-xs-12 col-md-9 content">
       <h1>Προσθήκη Μαθητών</h1>
<div id="add-student">
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :school %><br>
    <%= f.text_field :school, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :year %><br>
    <%= f.text_field :year, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :priority %><br>
    <%= f.text_field :priority, class: 'form-control' %>
  </div>
  
 <%= fields_for :student_attachments do |p| %>
     <div class="field">
       <%= p.label :avatar %><br>
       <%= p.file_field :avatar, :multiple => true %>
     <%end%>
     </div>
  <div class="actions">
    <%= f.submit "Καταχώρηση", class: "btn btn-primary" %>
  </div>
</div>

</div>
</div>
</div>
</section>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<% provide(:title, 'Ταυτότητα') %>
<% provide(:sbHeader, 'Ταυτότητα') %>
<% content_for :sbMenu do %>
    <%= link_to 'Οι Καθηγητές', taftotita_path %>
    <%= link_to 'Το φροντιστήριο', frontistirio_path %>
<% end %>
<div class="container">
    <div class="page-header">
      <h1>Επιτυχόντες</h1>
    </div>

    <div class="epitixontes">
          <% @students.each_slice(4) do |slice| %>
            <div class="row">
                <% slice.each do |student| %>
                  <div class="col-xs-12 col-md-3 item">
                  <%= image_tag student.student_attachments.first.avatar_url.to_s %>
                  <h2>  <%= sanitize student.first_name %>  <%= sanitize student.last_name %> </h2>
                  <h3>  <%= student.school %> </h3>
                  <h4> <% if model_signed_in? %>
                      <%= link_to 'Edit', edit_student_path(student)%>
                      <%end%>
                  </div>
                <% end %>
            </div>
          <%end%>
        <% if model_signed_in?%>
          <%= link_to 'Προσθήκη', new_student_path %>
          <%= link_to 'logout', destroy_model_session_path, :method=> :delete %>
        <%end%>
    </div>
  </div> <!-- /container -->

app/views/students/list.html.erb
<div class="sortable">
  <% @students.each do |student| %>
    <div class="panel-sortable" data-id="<%= student.id%>">
      <span class="my-handle">::</span>
      <%= student.first_name %>     <%= student.last_name %>
    </div>
  <%end%>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="sortable">
  <% @students.each do |student| %>
    <div class="panel-sortable" data-id="<%= student.id%>">
      <span class="my-handle">::</span>
      <%= student.first_name %>     <%= student.last_name %>
    </div>
  <%end%>
</div>