config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :panelladike2017s
  resources :suggested_posts
  resources :panelladikes
  resources :xeimwnas
  resources :kalokairis
  resources :latests
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'	
  devise_for :models, controllers: {sessions: 'models/sessions'}

  resources :students do
    put :order, on: :collection
  end

  get "home"=> "static_pages#home"
  
  get "lista" => "students#list"
  get "taftotita" => "static_pages#taftotita"
  get "frontistirio" => "static_pages#frontistirio"
  get "ecdl" => "static_pages#ecdl"
  get "contact" => "static_pages#contact"
  get "epitixontes"=>"students#index"
  get "dialekse_kateuthinsi"=>"static_pages#dialekse_kateuthinsi"
  get "analitika_thetiki"=>"static_pages#analitika_thetiki"

  get "programma" => "static_pages#programma"
  get "programma_lukeiou" => 'static_pages#lukeio'

  get "themata_ximeia"=>'static_pages#ximeia'
  get "themata_fusiki"=>'static_pages#fusiki'
  get "themata_mathimatika"=>'static_pages#mathimatika'
  get "themata_glwssa"=>'static_pages#glwssa'
  get "themata_latinika"=>'static_pages#latinika'
  get "themata_istoria"=>'static_pages#istoria'
  get "themata_biologia"=>'static_pages#biologia'
  get "themata_aoth"=>'static_pages#aoth'
  get "themata_arxaia"=>'static_pages#arxaia'
  get "themata_aep"=>'static_pages#aep'
  

  get "anthropistikes"=>'static_pages#anthropistikes'
  get "thetikes"=>'static_pages#thetikwn'
  get "oikonomias_pliroforikis"=>'static_pages#oikonomias'
 
 
  get "prosfora" => 'static_pages#prosfora'

end

app/models/kalokairi.rb
class Kalokairi < ActiveRecord::Base
end

app/controllers/kalokairis_controller.rb
class KalokairisController < ApplicationController
  before_action :set_kalokairi, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_model!, except: [:index]

  # GET /kalokairis
  # GET /kalokairis.json
  def index
    @kalokairis = Kalokairi.all
  end

  # GET /kalokairis/1
  # GET /kalokairis/1.json
  def show
  end

  # GET /kalokairis/new
  def new
    @kalokairi = Kalokairi.new
  end

  # GET /kalokairis/1/edit
  def edit
  end

  # POST /kalokairis
  # POST /kalokairis.json
  def create
    @kalokairi = Kalokairi.new(kalokairi_params)

    respond_to do |format|
      if @kalokairi.save
        format.html { redirect_to @kalokairi, notice: 'Kalokairi was successfully created.' }
        format.json { render :show, status: :created, location: @kalokairi }
      else
        format.html { render :new }
        format.json { render json: @kalokairi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kalokairis/1
  # PATCH/PUT /kalokairis/1.json
  def update
    respond_to do |format|
      if @kalokairi.update(kalokairi_params)
        format.html { redirect_to @kalokairi, notice: 'Kalokairi was successfully updated.' }
        format.json { render :show, status: :ok, location: @kalokairi }
      else
        format.html { render :edit }
        format.json { render json: @kalokairi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kalokairis/1
  # DELETE /kalokairis/1.json
  def destroy
    @kalokairi.destroy
    respond_to do |format|
      format.html { redirect_to kalokairis_url, notice: 'Kalokairi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kalokairi
      @kalokairi = Kalokairi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kalokairi_params
      params.require(:kalokairi).permit(:id,:body)
    end
end

app/helpers/kalokairis_helper.rb
module KalokairisHelper
end

app/views/kalokairis/_form.html.erb
<% provide(:title, 'Διαχειριστικό menu') %>
<% provide(:sbHeader, 'Διαχειριστικό menu') %>
<% content_for :sbMenu do %>
  <%= link_to 'Πρόγραμμα καλοκαιρινό', kalokairis_path %>
  <%= link_to 'Έξοδος', destroy_model_session_path , :method => :delete %>
    <% end %>

<%= form_for(@kalokairi) do |f| %>
  <% if @kalokairi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kalokairi.errors.count, "error") %> prohibited this latest from being saved:</h2>

      <ul>
      <% @kalokairi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav'%>
      </div>
     <div class="col-xs-12 col-md-9 content">
       <h1>Προσθήκη</h1>
<div id="add-student">
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, ckeditor: { language: 'us'}%>
  </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</div>
</div>
</div>
</section>
<% end %>

app/views/kalokairis/edit.html.erb
<h1>Editing Kalokairi</h1>

<%= render 'form' %>

<%= link_to 'Show', @kalokairi %> |
<%= link_to 'Back', kalokairis_path %>

app/views/kalokairis/index.html.erb
<% provide(:title, 'Πρόγραμμα') %>
<% provide(:sbHeader, 'Πρόγραμματα') %>
<% content_for :sbMenu do %>
  <%= link_to 'Καλοκαίρι', kalokairis_path %>
  <%= link_to 'Χειμώνας', xeimwnas_path %>
<% end %>

<section class="identity">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-3 sidebar" role="navigation">
        <%= render 'layouts/sidenav' %>  
      </div>
      <div class="col-xs-12 col-md-9 content">
        <div class="content-header">
          <h1 style="color:#FFA72D">Τα προγράμματα για τα θερινά τμήματα:</h1>   
        </div>
        <div class="news">
          <% @kalokairis.order(created_at: :desc).each do |kalokairi| %>
            <div class="item">
              <%= sanitize kalokairi.body%>
              <br>
              <%if model_signed_in?%>
                <div class="row">
                <%= link_to 'Show', kalokairi %>
                <%= link_to 'Edit', edit_kalokairi_path(kalokairi) %>
                <%= link_to 'Destroy', kalokairi, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div> <!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container -->

<%if model_signed_in?%>
<%= link_to 'New Kalokairi', new_kalokairi_path %>
<% end %>
</section>

app/views/kalokairis/new.html.erb
<h1>New Kalokairi</h1>

<%= render 'form' %>

<%= link_to 'Back', kalokairis_path %>

app/views/kalokairis/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kalokairi_path(@kalokairi) %> |
<%= link_to 'Back', kalokairis_path %>