config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :panelladike2017s
  resources :suggested_posts
  resources :panelladikes
  resources :xeimwnas
  resources :kalokairis
  resources :latests
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'	
  devise_for :models, controllers: {sessions: 'models/sessions'}

  resources :students do
    put :order, on: :collection
  end

  get "home"=> "static_pages#home"
  
  get "lista" => "students#list"
  get "taftotita" => "static_pages#taftotita"
  get "frontistirio" => "static_pages#frontistirio"
  get "ecdl" => "static_pages#ecdl"
  get "contact" => "static_pages#contact"
  get "epitixontes"=>"students#index"
  get "dialekse_kateuthinsi"=>"static_pages#dialekse_kateuthinsi"
  get "analitika_thetiki"=>"static_pages#analitika_thetiki"

  get "programma" => "static_pages#programma"
  get "programma_lukeiou" => 'static_pages#lukeio'

  get "themata_ximeia"=>'static_pages#ximeia'
  get "themata_fusiki"=>'static_pages#fusiki'
  get "themata_mathimatika"=>'static_pages#mathimatika'
  get "themata_glwssa"=>'static_pages#glwssa'
  get "themata_latinika"=>'static_pages#latinika'
  get "themata_istoria"=>'static_pages#istoria'
  get "themata_biologia"=>'static_pages#biologia'
  get "themata_aoth"=>'static_pages#aoth'
  get "themata_arxaia"=>'static_pages#arxaia'
  get "themata_aep"=>'static_pages#aep'
  

  get "anthropistikes"=>'static_pages#anthropistikes'
  get "thetikes"=>'static_pages#thetikwn'
  get "oikonomias_pliroforikis"=>'static_pages#oikonomias'
 
 
  get "prosfora" => 'static_pages#prosfora'

end

app/models/controller.rb
class Controller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/kalokairi.rb
class Kalokairi < ActiveRecord::Base
end

app/models/latest.rb
class Latest < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/panelladike.rb
class Panelladike < ActiveRecord::Base
end

app/models/panelladike2017.rb
class Panelladike2017 < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_attachments , dependent: :destroy
  accepts_nested_attributes_for :student_attachments, :allow_destroy => true

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates :year, presence: true, format: {with: /\d{4}/}
  validates :priority, numericality:{less_than_or_equal: 4}

  default_scope -> {order(priority: :asc)}
end

app/models/student_attachment.rb
class StudentAttachment < ActiveRecord::Base
  belongs_to :student
  mount_uploader :avatar, AvatarUploader
end

app/models/suggested_post.rb
class SuggestedPost < ActiveRecord::Base
end

app/models/xeimwna.rb
class Xeimwna < ActiveRecord::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, except: [:index, :new, :create]
  before_action :authenticate_model!, except: [:index]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_name, :body,:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #dialegei mia tuxaia eikona apo to fakelo me tis fwtografies gia to home page i opou allou to baloume
  def random_image
    image_files = %w( .jpg .JPG .png )
      files = Dir.entries(
            "#{Rails.root.join('app/assets/images/epitixontes/')}"
             ).delete_if { |x| !image_files.index(x[-4,4]) }
       @rnd_pic = files[rand(files.length)]
       @picTitle =  @rnd_pic.slice(0...(@rnd_pic.index('.')))
       @picTitle1 =  @rnd_pic.slice(0...(@rnd_pic.index('.')))
       @studName = @picTitle.split(' - ')[0]
       @studUni = @picTitle.split(' - ')[1]
      return @rnd_pic
  end

  def fetch_images
    image_files = %w( .jpg .JPG .png )
    files = Dir.entries(
          "#{Rails.root.join('app/assets/images/epitixontes-special/')}"
          ).sort.drop(2)

    files += Dir.entries(
          "#{Rails.root.join('app/assets/images/epitixontes/')}"
          ).sort.drop(2)

  end


  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ορόσημο Πειραιά"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title 
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/kalokairis_helper.rb
module KalokairisHelper
end

app/helpers/latests_helper.rb
module LatestsHelper
end

app/helpers/panelladikes_helper.rb
module PanelladikesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/xeimwnas_helper.rb
module XeimwnasHelper
end

app/views/layouts/_footer.html.erb
<!-- Start newsletter section -->
<section class="newsletter">
  <div class="container">
      <h3 class="pull-left">Μάθε τα νέα μας!</h3>

      <form class="form-inline pull-right">
        <input type="email" class="form-control" placeholder="Εγγραφή στο newsletter">
        <button type="submit" class="glyphicon glyphicon-triangle-right form-control btn"></button>
      </form>
  </div><!-- /.container -->
</section>

<!-- End newsletter section -->


<div class="footer">
  <div class="container">
    <div class="row">
      
      <div class="col-xs-12 col-md-3 footer-logo">
        <p>
          <span class="foot-subheader">ΠΙΣΤΟΠΟΙΗΜΕΝΑ ΦΡΟΝΤΙΣΤΗΡΙΑ</span>
          <span class="foot-header">ΟΡΟΣΗΜΟ</span>
        </p>
        <p class="foot-tel">210-4224752</p>
        <p class="foot-address">
          Αγ. Κωνσταντίνου 11, Πειραιάς
          (Δημοτικό Θέατρο)
        </p>
        <p class="foot-address">
          orosimop@otenet.gr
        </p>
        <div class="social-btns"></div>
      </div>

      <div class="col-xs-12 col-md-3">
        <h4>Η ταυτότητά μας</h4>
        <ul>
          <li><%= link_to 'Το Φροντιστήριο', frontistirio_path %></li>
          <li><%= link_to 'Αρχικό site', "http://old.orosimo-peiraia.gr" %></li>
          <li><%= link_to 'Επικοινωνία', contact_path %></li>
        </ul>
      </div>
      
      <div class="col-xs-12 col-md-3">
        <h4>Πρόγραμμα</h4>
        <ul>
          <li><%= link_to 'Πρόγραμμα Σπουδών', '#' %></li>
          <li><%= link_to 'Πανελλαδικές', '#' %></li>
          <li><%= link_to 'Καλοκαίρι', kalokairis_path %></li>
          <li><%= link_to 'ECDL', ecdl_path %></li>
          <li><%= link_to 'Προσφορά', '#' %></li>
        </ul>
      </div>
      
      <div class="col-xs-12 col-md-3">
        <h4>Εργαλεία</h4>
        <ul>
          <li><%= link_to 'Τεστ Επαγγελματικού Προσανατολισμού', 'https://www.youtube.com/channel/UCh0fw-LV_5iXczbizb9Jl_g' %></li>
          <li><%= link_to 'Οδηγός Σπουδών', courses_path %></li>
          <li><%= link_to 'Βιβλία', '#' %></li>
          <li><%= link_to 'Εικονικά Πειράματα', '#' %></li>
          <li><%= link_to 'Χρήσιμα Links', '#' %></li>
        </ul>
      </div>


    </div> <!-- /.row -->
  </div> <!-- /.container -->
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-103575401-1', 'auto');
    ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<!-- nav-top start -->
<nav id="nav-top" class="navbar navbar-white">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="menu-top" aria-expanded="false">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag 'logo.png', id: 'main-logo'%>
        <%= image_tag 'side-logo.png', id: 'side-logo'%>
      </a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Πανελλαδικές 2018", panelladike2017s_path, style:"color:#FFA72D" %></li>
        <li><%= link_to "Προτεινόμενα θέματα", suggested_posts_path %></li>
        <li><%= link_to "Κοινωνικό Ορόσημο", "http://www.koinoniko.orosimo-peiraia.gr" %></li>
        <li><%= link_to "Οδηγός Σπουδών", oikonomias_pliroforikis_path %></li>
        <li><%= link_to "Προσφορά", prosfora_path %></li>
        <li><%= link_to "Σύνδεση", new_model_session_path, id: 'login-btn' %></li>
      </ul>

    </div>
  </div>
</nav>
<!-- main nav end -->

<!-- secondary menu start -->
<nav id="nav-secondary" class="navbar navbar-yellow">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-collapse" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="nav-collapse">
      <ul class="nav nav-flat">
        <li><%= link_to "Η ταυτότητά μας", taftotita_path, role: 'presentation' %></li>
        <li><%= link_to "Τα νέα μας", latests_path, role: 'presentation' %></li>
        <li class="dropdown"><%= link_to raw('Πρόγραμμα Σπουδών'), '#' , {role: 'button', class: 'dropdown-toggle', "data-toggle": 'dropdown', "aria-haspopup": 'true', "aria-expanded": 'false'} %>
          <ul class="dropdown-menu">
            <li><%= link_to "Πανελλαδικές Εξετάσεις", panelladikes_path %></li>
            <li><%= link_to "Καλοκαίρι", kalokairis_path %></li>
            <li><%= link_to "Χειμώνας", xeimwnas_path %></li>
            <li><%= link_to "Προσφορά", prosfora_path %></li>
            <li><%= link_to "Προτεινόμενα Θέματα", suggested_posts_path %></li>
          </ul>
        </li>
        <li><%= link_to "ECDL", ecdl_path , role: 'presentation' %></li>
        <li><%#= link_to "Εργαλεία", '#' , role: 'presentation' %></li>
        <li><%= link_to "Επικοινωνία",contact_path , role: 'presentation' %></li>
        <li class="pull-right"><span class="menu-tel">210-4224752</span></li>
      </ul>
    </div>
  </div>
</nav>
<!-- secondary menu end -->

app/views/layouts/_sidenav.html.erb
<% if content_for? :sbMenu %>
  <nav class="nav-sidebar">
    <div class="sidebar-header">
      <h3><%= yield :sbHeader %></h3>
    </div>  
    <ul class="nav nav-flat nav-stacked">
      <li role="presentation"><%= yield :sbMenu %></li>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <title><%= full_title(yield(:title)) %></title>
</head>
  <body>
    <%= render 'layouts/header' %>
        <%= yield %>
   <%= render 'layouts/footer' %>
 </body>
</html>